version: '3.4'

services:
  website:
    image: "dapr.alltogether/website"
    build:
      context: .
      dockerfile: WebSite/Dockerfile
    ports:
      - 5000:80
    depends_on:      
      - redis
      - placement   
    # environment: 
    #   - DAPR_HTTP_PORT=3500
    #   - DAPR_GRPC_PORT=50000
    networks:
      - alltogether         
  website-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd", "-app-id", "website", "-app-port", "80", "-dapr-http-port", "3500", "-dapr-grpc-port", "50000", "-placement-host-address", "placement:50006", "-components-path", "./components", "-config", "./components/config.yaml"]    
    depends_on: 
      - website
    volumes:
      - "./components/:/components"            
    network_mode: "service:website" 
    
  counterservice:
    image: "dapr.alltogether/counterservice"
    build:
      context: .
      dockerfile: CounterService/Dockerfile
    ports:
      - 5002:80
    depends_on:
      - redis
      - placement
    # environment: 
    #   - DAPR_HTTP_PORT=3502
    #   - DAPR_GRPC_PORT=50002
    networks:
      - alltogether      
  counterservice-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd", "-app-id", "counterservice", "-app-port", "80", "-dapr-http-port", "3502", "-dapr-grpc-port", "50002", "-placement-host-address", "placement:50006", "-components-path", "./components", "-config", "./components/config.yaml"] 
    depends_on:       
      - counterservice
    volumes:
      - "./components/:/components"      
    network_mode: "service:counterservice"
  
  weatherservice:
    image: "dapr.alltogether/weatherservice"
    build:
      context: .
      dockerfile: WeatherService/Dockerfile
    ports:
      - 5003:80
    depends_on:      
      - placement    
    # environment: 
    #   - DAPR_HTTP_PORT=3503
    #   - DAPR_GRPC_PORT=50003
    networks:
      - alltogether      
  weatherservice-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd", "-app-id", "weatherservice", "-app-port", "80", "-dapr-http-port", "3503", "-dapr-grpc-port", "50003", "-placement-host-address", "placement:50006"]
    depends_on: 
      - weatherservice
    network_mode: "service:weatherservice"   

  ########################################################
  # Dapr placement service. Only when Actors are involved
  ########################################################
  placement:
    image: "daprio/dapr:latest"
    command: ["./placement", "-port", "50006"]
    ports:
      - 50006:50006
    networks:
      - alltogether
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - 6380:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - alltogether

  jaeger:
    image: jaegertracing/all-in-one:1.22
    # hostname: jaeger
    container_name: jaeger
    ports:
      - 16686:16686
      # - 9412:9411
    environment: 
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    depends_on: 
      - zipkin
    networks:
      - alltogether

  zipkin:
    image: openzipkin/zipkin
    # hostname: zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    ports:
      - 9410:9410
      - 9413:9411
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=9411
    networks:
      - alltogether

  dashboard:
    image: daprio/dashboard:latest
    # hostname: dashboard
    container_name: dashboard
    ports:
      - 8081:8080
    networks:
      - alltogether       

networks:
  alltogether:
