apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: default
spec:
  type: secretstores.azure.keyvault        
  version: v1
  metadata:
  - name: vaultName
    value: dapr-keyvault
  - name: spnTenantId
    value: "<TENAT-ID>"
  - name: spnClientId
    value: "<SERVICE-PRINCIPAL-NAME-ID>"
  - name: spnCertificateFile
    value : "C:\\Users\\jlguerrero\\dapr-keyvault.pfx"