apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bindingeventdemo
  namespace: default
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: storageAccount
    value: "daprbindings"
  - name: storageAccessKey
    value: "<AZURE-STORATE-ACCOUNT-KEY>"
  - name: queue
    value: "queuedemo1"
  - name: ttlInSeconds
    value: "60"
