apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: counter-store
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost      
      value: redis:6379 # <- Defined inside docker compose file
    - name: redisPassword
      value: ""
    # - name: actorStateStore
    #   value: "true"