apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master.default.svc.cluster.local:6379
  - name: redisPassword
    # value: ""  
    secretKeyRef:
      name: redis
      key: redis-password
#   - name: actorStateStore
#     value: "true"
#   - name: enableTLS # <-- This is the important part missing in the docs
#     value: "true"           
# auth:
#   secretStore: kubernetes