apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      # value: localhost:6379 # <- localhost
      value: redis:6379 # <- docker compose
    - name: redisPassword
      value: ""